{
 "title": "中台k8s集群精细化运营指标",
 "tags": [
  "中台",
  "资源"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Label", "label": "标签", "query": "rcmd,minigame,big-data" },
   {
    "name": "Node",
    "label": "节点",
    "query": "label_values(kube_node_labels{label_dev_groups=~\"$Label\"},node)"
   },
   {
    "name": "Namespaces",
    "label": "命名空间",
    "query": "label_values(kube_namespace_labels{label_dev_groups=~\"$Label\"},namespace)"
   },
   {
    "name": "Deploy",
    "label": "无状态应用名称",
    "query": "label_values(kube_deployment_labels{namespace=~\"$Namespaces\"}, deployment)"
   },
   {
    "name": "Stateful",
    "label": "有状态应用",
    "query": "label_values(kube_statefulset_labels{namespace=~\"$Namespaces\"}, statefulset)"
   },
   { "name": "TopN", "label": "TopN", "query": "10,20,30,50" }
  ]
 },
 "panels": [
  { "title": "节点池汇总", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点池CPU使用率和分配率%",
   "type": "gauge",
   "description": "分配率过高则表示整个集群无法部署新的应用，使用率过低则表示整个集群资源利用率低",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[1d]))*100/sum(machine_cpu_cores{node=~\"^$Node$\"})",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"})*100 / sum (machine_cpu_cores{node=~\"^$Node$\"})",
     "legendFormat": "CPU分配率"
    }
   ]
  },
  {
   "title": "节点池内存使用率%",
   "type": "gauge",
   "description": "分配率过高则表示整个集群无法部署新的应用，使用率过低则表示整个集群资源利用率低",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"})*100 / sum (machine_memory_bytes{node=~\"^$Node$\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"})*100 / sum (machine_memory_bytes{node=~\"^$Node$\"})",
     "legendFormat": "内存分配率"
    }
   ]
  },
  {
   "title": "节点",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "节点CPU使用率%",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[5m]))by(node)*100/sum(machine_cpu_cores{node=~\"^$Node$\"})by(node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "节点CPU使用率",
     "type": "table",
     "description": "峰值使用率在30%~40%左右最佳",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[5m]))by(node)*100/sum(machine_cpu_cores{node=~\"^$Node$\"})by(node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "节点CPU分配率%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"})by(node)*100/sum(machine_cpu_cores{node=~\"^$Node$\"})by(node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "节点内存使用率%",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"})by (node)*100 / sum (machine_memory_bytes{node=~\"^$Node$\"})by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "节点内存使用率",
     "type": "table",
     "description": "内存峰值使用率在30%~60%左右最佳",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"})by (node)*100 / sum (machine_memory_bytes{node=~\"^$Node$\"})by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "节点内存分配率%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"})by (node)*100 / sum (machine_memory_bytes{node=~\"^$Node$\"})by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  { "title": "Pod容器信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pod的容器CPU使用率%（最小TopN）",
   "type": "graph",
   "description": "指标为：CPU使用率/CPU限制率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($TopN,sum(irate(container_cpu_usage_seconds_total{namespace=~\"$Namespaces\"}[10m])) by (pod)*100/sum(container_spec_cpu_quota{namespace=~\"$Namespaces\"}/100000) by (pod))"
    }
   ]
  },
  {
   "title": "Pod的容器CPU使用率%",
   "type": "table",
   "description": "峰值使用率在30%~80%左右最佳",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$Namespaces\"}[1h])) by (pod)*100/sum(container_spec_cpu_quota{namespace=~\"$Namespaces\"}/100000) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod的容器内存使用率%（最小TopN）",
   "type": "graph",
   "description": "指标为：内存使用率/内存限制率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($TopN, sum(container_memory_rss{namespace=~\"$Namespaces\",container!=\"\"}) by (pod)/sum(container_spec_memory_limit_bytes{namespace=~\"$Namespaces\"}) by (pod) *100)"
    }
   ]
  },
  {
   "title": "Pod的容器内存使用率%",
   "type": "table",
   "description": "峰值使用率在30%~60%左右最佳",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"$Namespaces\",container!=\"\"}) by (pod)/sum(container_spec_memory_limit_bytes{namespace=~\"$Namespaces\"}) by (pod) *100",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}